# Generated by Django 5.0.6 on 2024-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('planned_hours', models.IntegerField()),
                ('actual_hours', models.IntegerField()),
                ('hours_difference', models.IntegerField()),
                ('budget', models.FloatField()),
                ('sells', models.FloatField()),
                ('money_difference', models.FloatField()),
            ],
        ),
    ]
